package br.ucsal.compiladores.lexer;

public enum TokenType {
    // Palavras Reservadas (PRS)
    PRS_PROGRAM("PRS14"),
    PRS_END_PROGRAM("PRS15"),
    PRS_DECLARATIONS("PRS12"),
    PRS_END_DECLARATIONS("PRS13"),
    PRS_FUNCTIONS("PRS16"),
    PRS_END_FUNCTIONS("PRS17"),
    PRS_VAR_TYPE("PRS10"),
    PRS_FUNC_TYPE("PRS11"),
    PRS_PARAM_TYPE("PRS09"),
    PRS_INTEGER("PRS01"),
    PRS_REAL("PRS02"),
    PRS_STRING("PRS03"),
    PRS_BOOLEAN("PRS05"),
    PRS_CHARACTER("PRS06"),
    PRS_VOID("PRS07"),
    PRS_TRUE("PRS08"),
    PRS_FALSE("PRS04"),
    PRS_IF("PRS20"),
    PRS_ELSE("PRS21"),
    PRS_ENDIF("PRS22"),
    PRS_WHILE("PRS23"),
    PRS_ENDWHILE("PRS24"),
    PRS_RETURN("PRS19"),
    PRS_BREAK("PRS25"),
    PRS_PRINT("PRS26"),
    PRS_ENDFUNCTION("PRS18"),

    // Símbolos Reservados (SRS)
    SRS_SEMICOLON("SRS01"),
    SRS_COMMA("SRS02"),
    SRS_COLON("SRS03"),
    SRS_ASSIGNMENT("SRS04"),
    SRS_QUESTION_MARK("SRS05"),
    SRS_LEFT_PARENTHESIS("SRS06"),
    SRS_RIGHT_PARENTHESIS("SRS07"),
    SRS_LEFT_BRACKET("SRS08"),
    SRS_RIGHT_BRACKET("SRS09"),
    SRS_LEFT_BRACE("SRS10"),
    SRS_RIGHT_BRACE("SRS11"),
    SRS_PLUS("SRS12"),
    SRS_MINUS("SRS13"),
    SRS_MULTIPLICATION("SRS14"),
    SRS_DIVISION("SRS15"),
    SRS_MODULO("SRS16"),
    SRS_EQUAL_COMPARISON("SRS17"),
    SRS_NOT_EQUAL("SRS18"),
    SRS_LESS_THAN("SRS19"),
    SRS_LESS_THAN_OR_EQUAL("SRS20"),
    SRS_GREATER_THAN("SRS21"),
    SRS_GREATER_THAN_OR_EQUAL("SRS22"),

    // Identificadores (IDN)
    IDN_PROGRAM_NAME("IDN01"),
    IDN_VARIABLE("IDN02"),
    IDN_FUNCTION_NAME("IDN03"),
    IDN_INT_CONST("IDN04"),
    IDN_REAL_CONST("IDN05"),
    IDN_STRING_CONST("IDN06"),
    IDN_CHAR_CONST("IDN07"),

    // Controle
    EOF("EOF00"),
    UNKNOWN("ERR01");

    private final String code;

    TokenType(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
